---
# Configure homebrew for multiuser usage
#
- name: Disabling brew analytics
  command:
    argv:
      - brew
      - analytics
      - "off"

- name: Create a group for homebrew users
  ansible.builtin.group:
    name: somegroup
    state: present
